// Utility to dynamically build iCalendar (.ics) files for attachments

export function buildIcsString(
    employeeName: string,
    leaveType: string,
    startDate: Date,
    endDate: Date
): string {
    // Format dates correctly for ICS (YYYYMMDDTHHMMSSZ)
    const formatIcsDate = (date: Date) => {
        return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
    };

    const start = formatIcsDate(startDate);

    // For all-day events like PTO, the end date is exclusive in ICS, so we add 1 day
    const end = new Date(endDate);
    end.setDate(end.getDate() + 1);
    const endFormatted = formatIcsDate(end);

    const dtStamp = formatIcsDate(new Date());
    const uid = `${dtStamp}-${Math.random().toString(36).substring(2, 11)}@kaprahrms.com`;

    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Kapra HRMS//Leave Calendar Integration//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VEVENT
UID:${uid}
DTSTAMP:${dtStamp}
DTSTART;VALUE=DATE:${start.substring(0, 8)}
DTEND;VALUE=DATE:${endFormatted.substring(0, 8)}
SUMMARY:${employeeName} - ${leaveType} (OOTO)
DESCRIPTION:${employeeName} is scheduled to be out of office for ${leaveType}. This is an automated calendar block generated by Kapra HRMS.
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR`;

    return icsContent.trim();
}
